# Users schema

# --- !Ups
CREATE SCHEMA STORE;

CREATE TABLE STORE.USERS (
    ID                       BIGINT(20) NOT NULL AUTO_INCREMENT,
    EMAIL                    VARCHAR(200),
    NAME                     VARCHAR(200),
    NAME_KANA                VARCHAR(200),
    TEAM                     VARCHAR(200),
    HITOTALENT_ID            VARCHAR(200),
    GENDAR                   VARCHAR(200),
    AGE                      INT(11),
    ACCESS_TOKEN             VARCHAR(200),
    REFRESH_TOKEN            VARCHAR(200),
    ACCESS_TOKEN_EXPIRES_IN  VARCHAR(200),
    REFRESH_TOKEN_EXPIRES_IN VARCHAR(200),
    IS_VALID                 BOOLEAN NOT NULL DEFAULT true,
    
    PRIMARY KEY (ID)
);

CREATE TABLE STORE.TAG (
    ID       BIGINT(20) NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(200),
    ALIAS    VARCHAR(200),
    IS_VALID BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (ID)
);

CREATE TABLE STORE.EVENT (
    ID         BIGINT(20) NOT NULL AUTO_INCREMENT,
    EVENT_DATE VARCHAR(200),
    EVENT_TYPE INT(11),
    IS_VALID   BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (ID)
);

CREATE TABLE STORE.BIOTOP (
    ID       BIGINT(20) NOT NULL AUTO_INCREMENT,
    EVENT_ID BIGINT(20),
    TAG_ID   BIGINT(20),
    IS_VALID BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (ID),
    FOREIGN KEY (EVENT_ID) REFERENCES STORE.EVENT(ID) ON DELETE RESTRICT,
    FOREIGN KEY (TAG_ID)   REFERENCES STORE.TAG(ID)   ON DELETE RESTRICT
);

CREATE TABLE STORE.USER_TAG_MAP (
    USER_ID  BIGINT(20) NOT NULL,
    TAG_ID   BIGINT(20) NOT NULL,
    IS_VALID BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (USER_ID, TAG_ID),
    FOREIGN KEY (USER_ID)  REFERENCES STORE.USERS(ID) ON DELETE RESTRICT,
    FOREIGN KEY (TAG_ID)   REFERENCES STORE.TAG(ID)  ON DELETE RESTRICT
);

CREATE TABLE STORE.USER_EVENT_MAP (
    USER_ID  BIGINT(20) NOT NULL,
    EVENT_ID BIGINT(20) NOT NULL,
    IS_VALID BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (USER_ID, EVENT_ID),
    FOREIGN KEY (USER_ID)  REFERENCES STORE.USERS(ID)  ON DELETE RESTRICT,
    FOREIGN KEY (EVENT_ID) REFERENCES STORE.EVENT(ID) ON DELETE RESTRICT
);

CREATE TABLE STORE.USER_BIOTOP_MAP (
    USER_ID   BIGINT(20) NOT NULL,
    BIOTOP_ID BIGINT(20) NOT NULL,
    IS_VALID  BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (USER_ID, BIOTOP_ID),
    FOREIGN KEY (USER_ID)   REFERENCES STORE.USERS(ID)   ON DELETE RESTRICT,
    FOREIGN KEY (BIOTOP_ID) REFERENCES STORE.BIOTOP(ID) ON DELETE RESTRICT
);

# --- !Downs

DROP TABLE STORE.USER_BIOTOP_MAP;
DROP TABLE STORE.USER_EVENT_MAP;
DROP TABLE STORE.USER_TAG_MAP;
DROP TABLE STORE.BIOTOP;
DROP TABLE STORE.EVENT;
DROP TABLE STORE.TAG;
DROP TABLE STORE.USERS;

DROP SCHEMA STORE;
